ci:
    skip: [ggshield, pylint, terraform_fmt, terraform_validate, terraform_providers_lock]

repos:

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint
        name: markdown linting

  - repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
      - id: doctoc
        name: update toc
        args: ["--update-only"]

  - repo: https://github.com/gitguardian/ggshield
    rev: v1.13.6
    hooks:
      - id: ggshield
        name: gitguardian scanning

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        name: trailing whitespace
      - id: end-of-file-fixer
        name: end of file fixer
      - id: check-added-large-files
        name: check added large files
      - id: check-yaml
        name: check yaml
      - id: check-json
        name: check json

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.76.0
    hooks:
    - id: terraform_fmt
      name: terraform formatting
      args:
        - --args=-diff
        - --args=-write=true
    - id: terraform_validate
      name: terraform validation
      args:
        - --args=-json
    - id: terraform_providers_lock
      name: terraform providers lock
      args:
          - --args=-platform=darwin_amd64
          - --args=-platform=linux_amd64

  -  repo: https://github.com/psf/black
     rev: 22.10.0
     hooks:
      - id: black

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: ["-rn", "-sn"]

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-beta.5
    hooks:
      - id: go-mod-tidy
        name: golang tidying
      - id: golangci-lint-repo-mod
        name: golang linting
